apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: ceph.com/rbd
parameters:
  monitors: 10.0.8.61:6789, 10.0.8.66:6789, 10.0.8.68:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: ceph
  pool: kube
  userId: kube
  userSecretName: ceph-secret-kube
  userSecretNamespace: ceph
  imageFormat: "2"
  imageFeatures: layering